server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
#  port: 8083
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-components: always
#      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-service-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop